#!/usr/bin/env python3
"""Declarative coverage map for the Windows real-WPS Action suite.

The lists in this module are intentionally independent from action_manifest.json.
The ordinary CI test compares both inventories so a newly added Action cannot be
silently omitted from real-machine testing.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Tuple, Union


@dataclass(frozen=True)
class Scenario:
    owner: str
    name: str
    actions: Tuple[str, ...]


SCENARIOS = (
    Scenario(
        "bridge",
        "Bridge connectivity",
        (
            "ping",
            "wireCheck",
        ),
    ),
    Scenario(
        "excel",
        "Excel workbook lifecycle and discovery",
        (
            "getAppInfo",
            "reconnect",
            "createWorkbook",
            "getOpenWorkbooks",
            "getActiveWorkbook",
            "getContext",
            "getSelection",
            "switchWorkbook",
            "openWorkbook",
        ),
    ),
    Scenario(
        "excel",
        "Excel cell, range, and formula data",
        (
            "setCellValue",
            "getCellValue",
            "setRangeData",
            "getRangeData",
            "setFormula",
            "getFormula",
            "setArrayFormula",
            "evaluateFormula",
            "diagnoseFormula",
            "setSelectedText",
            "getSelectedText",
            "clearRange",
            "findReplace",
            "fillSeries",
            "autoSum",
            "cleanData",
            "removeDuplicates",
            "textToColumns",
            "transpose",
            "subtotal",
            "sortRange",
            "autoFilter",
        ),
    ),
    Scenario(
        "excel",
        "Excel sheets and structural editing",
        (
            "createSheet",
            "getSheetList",
            "switchSheet",
            "renameSheet",
            "moveSheet",
            "copySheet",
            "insertRows",
            "deleteRows",
            "insertColumns",
            "deleteColumns",
            "hideRows",
            "showRows",
            "groupRows",
            "hideColumns",
            "showColumns",
            "mergeCells",
            "unmergeCells",
            "deleteSheet",
        ),
    ),
    Scenario(
        "excel",
        "Excel formatting and page layout",
        (
            "setCellFormat",
            "setCellStyle",
            "setNumberFormat",
            "setBorder",
            "setColumnWidth",
            "setRowHeight",
            "setHyperlink",
            "addConditionalFormat",
            "addDataValidation",
            "freezePanes",
            "setZoom",
            "setPrintArea",
        ),
    ),
    Scenario(
        "excel",
        "Excel review, names, and protection",
        (
            "addCellComment",
            "getCellComments",
            "getCellInfo",
            "deleteCellComment",
            "createNamedRange",
            "lockCells",
            "protectSheet",
            "unprotectSheet",
            "protectWorkbook",
        ),
    ),
    Scenario(
        "excel",
        "Excel clipboard, media, charts, and pivots",
        (
            "copyRange",
            "pasteRange",
            "insertExcelImage",
            "exportRangeAsImage",
            "createChart",
            "updateChart",
            "exportChartAsImage",
            "createPivotTable",
            "updatePivotTable",
        ),
    ),
    Scenario(
        "excel",
        "Excel persistence and conversion",
        (
            "saveAs",
            "save",
            "convertToPDF",
            "convertFormat",
            "closeWorkbook",
        ),
    ),
    Scenario(
        "ppt",
        "PPT presentation lifecycle and discovery",
        (
            "getAppInfo",
            "reconnect",
            "createPresentation",
            "getOpenPresentations",
            "getSlideCount",
            "switchPresentation",
            "openPresentation",
        ),
    ),
    Scenario(
        "ppt",
        "PPT slide lifecycle and content",
        (
            "addSlide",
            "duplicateSlide",
            "moveSlide",
            "switchSlide",
            "getSlideInfo",
            "getSlideTitle",
            "setSlideTitle",
            "setSlideSubtitle",
            "setSlideContent",
            "setSlideNotes",
            "getSlideNotes",
            "setSlideLayout",
            "insertSlidesFromFile",
            "deleteSlide",
        ),
    ),
    Scenario(
        "ppt",
        "PPT text boxes and text operations",
        (
            "addTextBox",
            "getTextBoxes",
            "setTextBoxText",
            "setTextBoxStyle",
            "deleteTextBox",
            "setSelectedText",
            "getSelectedText",
            "findPptText",
            "replacePptText",
            "unifyFont",
            "setFontColor",
        ),
    ),
    Scenario(
        "ppt",
        "PPT shapes and layout",
        (
            "addShape",
            "getShapes",
            "setShapeText",
            "setShapePosition",
            "setShapeFill",
            "setShapeGradient",
            "setShapeBorder",
            "setShapeShadow",
            "setShapeTransparency",
            "setShapeStyle",
            "setShapeZOrder",
            "duplicateShape",
            "alignShapes",
            "distributeShapes",
            "smartDistribute",
            "deleteShape",
            "groupShapes",
        ),
    ),
    Scenario(
        "ppt",
        "PPT images, tables, charts, and links",
        (
            "insertPptImage",
            "insertImage",
            "replacePptImage",
            "setImageStyle",
            "deletePptImage",
            "insertPptTable",
            "setPptTableCell",
            "getPptTableCell",
            "setPptTableCellStyle",
            "setPptTableRowStyle",
            "setPptTableStyle",
            "insertPptChart",
            "setPptChartData",
            "setPptChartStyle",
            "addPptHyperlink",
            "removePptHyperlink",
        ),
    ),
    Scenario(
        "ppt",
        "PPT diagrams and visual components",
        (
            "createFlowChart",
            "createOrgChart",
            "createTimeline",
            "createStyledTable",
            "createKpiCards",
            "createProgressBar",
            "createGauge",
            "createDonutChart",
            "createMiniCharts",
            "createGrid",
            "create3DText",
            "set3DDepth",
            "set3DRotation",
            "set3DMaterial",
        ),
    ),
    Scenario(
        "ppt",
        "PPT theme, master, and slide decoration",
        (
            "setSlideBackground",
            "setBackgroundColor",
            "setBackgroundGradient",
            "setBackgroundImage",
            "setSlideTheme",
            "applyColorScheme",
            "setSlideSize",
            "getSlideMaster",
            "setMasterBackground",
            "addMasterElement",
            "setPptFooter",
            "setPptDateTime",
            "setSlideNumber",
            "addPageIndicator",
            "addTitleDecoration",
            "autoLayout",
            "beautifySlide",
            "beautifyAllSlides",
            "autoBeautifySlide",
        ),
    ),
    Scenario(
        "ppt",
        "PPT animation, transitions, and presenting",
        (
            "addAnimation",
            "addAnimationPreset",
            "addEmphasisAnimation",
            "getAnimations",
            "setAnimationOrder",
            "removeAnimation",
            "setSlideTransition",
            "applyTransitionToAll",
            "removeSlideTransition",
            "startSlideShow",
        ),
    ),
    Scenario(
        "ppt",
        "PPT persistence and export",
        (
            "exportSlideAsImage",
            "saveAs",
            "save",
            "convertToPDF",
            "convertFormat",
            "closePresentation",
        ),
    ),
    Scenario(
        "word",
        "Word document lifecycle and discovery",
        (
            "getAppInfo",
            "reconnect",
            "createDocument",
            "getOpenDocuments",
            "getActiveDocument",
            "switchDocument",
            "openDocument",
        ),
    ),
    Scenario(
        "word",
        "Word content and document structure",
        (
            "insertText",
            "getDocumentText",
            "getDocumentParagraphs",
            "insertPageBreak",
            "insertSectionBreak",
            "insertTable",
            "insertImage",
            "insertHeader",
            "insertFooter",
            "insertBookmark",
            "replaceBookmarkContent",
            "generateTOC",
        ),
    ),
    Scenario(
        "word",
        "Word formatting and page layout",
        (
            "setFont",
            "setTextColor",
            "setParagraph",
            "setLineSpacing",
            "applyStyle",
            "setPageSetup",
            "setSelectedText",
            "getSelectedText",
        ),
    ),
    Scenario(
        "word",
        "Word review, search, and fields",
        (
            "findInDocument",
            "findReplace",
            "addComment",
            "smartFillField",
        ),
    ),
    Scenario(
        "word",
        "Word persistence and conversion",
        (
            "saveAs",
            "save",
            "convertToPDF",
            "convertFormat",
        ),
    ),
)


def iter_declared_actions() -> Iterator[Tuple[str, str]]:
    """Yield every explicitly declared ``(owner, action)`` identity."""

    for scenario in SCENARIOS:
        for action in scenario.actions:
            yield scenario.owner, action


def scenarios_for(owner: str) -> Tuple[Scenario, ...]:
    """Return scenarios for one Action owner."""

    return tuple(scenario for scenario in SCENARIOS if scenario.owner == owner)


def default_suite_state(artifact_dir: Union[str, Path]) -> dict:
    """Return deterministic fixture identities used before live results arrive."""

    root = Path(artifact_dir).resolve()
    return {
        "artifact_dir": str(root),
        "fixture_image": str(root / "fixture.png"),
        "excel_main_path": str(root / "excel-main.xlsx"),
        "excel_secondary_path": str(root / "excel-secondary.xlsx"),
        "excel_final_path": str(root / "excel-final.xlsx"),
        "excel_pdf_path": str(root / "excel.pdf"),
        "excel_converted_path": str(root / "excel-converted.xlsx"),
        "excel_chart_image": str(root / "excel-chart.png"),
        "excel_range_image": str(root / "excel-range.png"),
        "excel_main_name": "excel-main.xlsx",
        "excel_main_sheet": "Sheet1",
        "excel_chart_name": "Chart 1",
        "excel_pivot_name": "PivotTable1",
        "ppt_main_path": str(root / "ppt-main.pptx"),
        "ppt_secondary_path": str(root / "ppt-secondary.pptx"),
        "ppt_final_path": str(root / "ppt-final.pptx"),
        "ppt_pdf_path": str(root / "ppt.pdf"),
        "ppt_converted_path": str(root / "ppt-converted.pptx"),
        "ppt_slide_image": str(root / "ppt-slide.png"),
        "ppt_main_name": "ppt-main.pptx",
        "ppt_slide": 1,
        "ppt_slide_count": 1,
        "ppt_duplicate_slide": 2,
        "ppt_textbox_id": 1,
        "ppt_shape_id": 1,
        "ppt_duplicate_shape_id": 2,
        "ppt_image_id": 1,
        "ppt_replace_image_id": 1,
        "ppt_table_id": 1,
        "ppt_chart_id": 1,
        "ppt_animation_shape_id": 1,
        "word_main_path": str(root / "word-main.docx"),
        "word_secondary_path": str(root / "word-secondary.docx"),
        "word_open_path": str(root / "word-open.docx"),
        "word_final_path": str(root / "word-final.docx"),
        "word_pdf_path": str(root / "word.pdf"),
        "word_converted_path": str(root / "word-converted.docx"),
        "word_main_name": "word-main.docx",
    }


def _excel_params(action: str, state: dict) -> dict:
    p = {
        "addCellComment": {"cell": "R1", "comment": "WPS full suite comment"},
        "addConditionalFormat": {"range": "B2:B5", "condition": 5},
        "addDataValidation": {"range": "S2:S5", "type": "list", "formula": "A,B,C"},
        "autoFilter": {"range": "A1:B5", "field": 1, "criteria": "A"},
        "autoSum": {"range": "B2:B5", "targetCell": "B6"},
        "cleanData": {"range": "G1:H5", "operations": ["trim", "remove_duplicates", "remove_empty_rows"]},
        "clearRange": {"range": "Z1:Z2", "type": "all"},
        "closeWorkbook": {"name": state["excel_main_name"], "save": False},
        "convertFormat": {"outputPath": state["excel_converted_path"], "overwrite": True, "targetFormat": "xlsx"},
        "convertToPDF": {"outputPath": state["excel_pdf_path"], "overwrite": True},
        "copyRange": {"sourceRange": "A1:B2", "targetRange": "AA1:AB2"},
        "copySheet": {"name": "SuiteRenamed", "newName": "SuiteCopy"},
        "createChart": {
            "dataRange": "A1:B5",
            "chartType": "column",
            "title": "WPS full suite chart",
            "showLegend": True,
            "showDataLabels": True,
            "position": {"left": 400, "top": 20, "width": 480, "height": 300},
        },
        "createNamedRange": {"name": "WpsSuiteValues", "range": "B2:B5"},
        "createPivotTable": {
            "sourceRange": "A1:B5",
            "destinationCell": "U1",
            "rowFields": ["Category"],
            "valueFields": [{"field": "Value", "aggregation": "SUM"}],
        },
        "createSheet": {"name": "SuiteTemp"},
        "deleteCellComment": {"cell": "R1"},
        "deleteColumns": {"column": 25, "count": 1},
        "deleteRows": {"row": 25, "count": 1},
        "deleteSheet": {"name": "SuiteCopy"},
        "diagnoseFormula": {"cell": "C2"},
        "evaluateFormula": {"formula": "=SUM(1,2,3)"},
        "exportChartAsImage": {"chartName": state["excel_chart_name"], "outputPath": state["excel_chart_image"], "format": "PNG"},
        "exportRangeAsImage": {"range": "A1:B5", "outputPath": state["excel_range_image"], "format": "PNG"},
        "fillSeries": {"sourceRange": "E1:E2", "targetRange": "E1:E5"},
        "findReplace": {"find": "EXCEL_FIND_TOKEN", "replace": "EXCEL_REPLACED_TOKEN", "matchCase": True},
        "freezePanes": {"freeze": True, "row": 2, "column": 1},
        "getCellComments": {"range": "R1:R2"},
        "getCellInfo": {"cell": "B2"},
        "getCellValue": {"row": 10, "col": 1},
        "getFormula": {"cell": "C2"},
        "getRangeData": {"range": "A1:B5"},
        "groupRows": {"range": "20:22"},
        "hideColumns": {"column": 24, "count": 1, "hide": True},
        "hideRows": {"row": 20, "count": 1, "hide": True},
        "insertColumns": {"column": 25, "count": 1},
        "insertExcelImage": {"imagePath": state["fixture_image"], "range": "A30"},
        "insertRows": {"row": 25, "count": 1},
        "lockCells": {"range": "B2:B5", "lock": True},
        "mergeCells": {"range": "T20:U20"},
        "moveSheet": {"name": "SuiteRenamed", "position": 1},
        "openWorkbook": {"filePath": state["excel_secondary_path"]},
        "pasteRange": {"targetRange": "AE1"},
        "protectSheet": {"protect": True, "password": "wps-suite"},
        "protectWorkbook": {"protect": True, "password": "wps-suite"},
        "removeDuplicates": {"range": "I1:J5", "columns": [1, 2], "hasHeader": True},
        "renameSheet": {"oldName": "SuiteTemp", "newName": "SuiteRenamed"},
        "saveAs": {"filePath": state["excel_final_path"], "overwrite": True},
        "setArrayFormula": {"range": "C6:C7", "formula": "=ROW(A1:A2)"},
        "setBorder": {"range": "A1:B5", "borderStyle": "thin", "color": "#4472C4", "position": "all"},
        "setCellFormat": {"range": "A1:B1", "format": {"bold": True, "fontColor": "#FFFFFF", "bgColor": "#4472C4", "horizontalAlignment": "center"}},
        "setCellStyle": {"range": "B2:B5", "style": "Good"},
        "setCellValue": {"row": 10, "col": 1, "value": 42},
        "setColumnWidth": {"column": 1, "width": 18},
        "setFormula": {"cell": "C2", "formula": "=B2*2"},
        "setHyperlink": {"cell": "T1", "address": "https://example.com", "textToDisplay": "WPS suite link"},
        "setNumberFormat": {"range": "B2:B6", "format": "0.00"},
        "setPrintArea": {"range": "A1:U25"},
        "setRangeData": {"range": "A1:B5", "data": [["Category", "Value"], ["A", 10], ["B", 20], ["C", 15], ["A", 12]]},
        "setRowHeight": {"row": 1, "height": 24},
        "setSelectedText": {"text": "EXCEL_SELECTION_TOKEN"},
        "setZoom": {"percent": 90},
        "showColumns": {"column": 24, "count": 1},
        "showRows": {"row": 20, "count": 1},
        "sortRange": {"range": "A1:B5", "column": 2, "ascending": True},
        "subtotal": {"range": "N1:O5", "groupBy": 1, "function": "sum", "summaryRange": "O2:O5"},
        "switchSheet": {"name": state["excel_main_sheet"]},
        "switchWorkbook": {"name": state["excel_main_name"]},
        "textToColumns": {"range": "K1:K3", "delimiter": ","},
        "transpose": {"range": "AJ1:AK2"},
        "unmergeCells": {"range": "T20:U20"},
        "unprotectSheet": {"password": "wps-suite"},
        "updateChart": {"chartName": state["excel_chart_name"], "title": "WPS full suite chart updated", "showLegend": False},
        "updatePivotTable": {"tableName": state["excel_pivot_name"]},
    }
    return dict(p.get(action, {}))


def _ppt_params(action: str, state: dict) -> dict:
    slide = int(state["ppt_slide"])
    shape = int(state["ppt_shape_id"])
    p = {
        "addAnimation": {"slideIndex": slide, "shapeIndex": int(state["ppt_animation_shape_id"])},
        "addAnimationPreset": {"slideIndex": slide, "shapeIndex": int(state["ppt_animation_shape_id"])},
        "addEmphasisAnimation": {"slideIndex": slide, "shapeIndex": int(state["ppt_animation_shape_id"])},
        "addPptHyperlink": {"slideIndex": slide, "shapeIndex": int(state["ppt_table_id"]), "url": "https://example.com"},
        "addShape": {"slideIndex": slide, "shapeType": "rectangle", "x": 60, "y": 80, "width": 180, "height": 100},
        "addSlide": {"layout": "title_content", "title": "WPS suite added slide"},
        "addTextBox": {"slideIndex": slide, "x": 60, "y": 360, "width": 360, "height": 60, "text": "PPT_TEXTBOX_TOKEN"},
        "alignShapes": {"slideIndex": slide, "align": "top"},
        "applyColorScheme": {"color": "#4472C4"},
        "applyTransitionToAll": {"transitionType": 1},
        "closePresentation": {"save": False},
        "convertFormat": {"outputPath": state["ppt_converted_path"], "overwrite": True, "targetFormat": "pptx"},
        "convertToPDF": {"outputPath": state["ppt_pdf_path"], "overwrite": True},
        "create3DText": {"slideIndex": slide, "text": "WPS 3D"},
        "createDonutChart": {"slideIndex": slide, "x": 450, "y": 300, "chartType": "doughnut"},
        "createFlowChart": {"slideIndex": slide, "steps": ["Start", "Process", "Finish"]},
        "createGauge": {"slideIndex": slide, "x": 500, "y": 80, "diameter": 160},
        "createGrid": {"slideIndex": slide, "rows": 2, "cols": 3, "x": 40, "y": 40, "cellWidth": 100, "cellHeight": 60},
        "createKpiCards": {"slideIndex": slide, "cards": [{"title": "Revenue", "value": 120}, {"title": "Growth", "value": "12%"}]},
        "createMiniCharts": {"slideIndex": slide, "x": 350, "y": 250, "chartType": "line"},
        "createOrgChart": {"slideIndex": slide, "steps": ["CEO", "Team A", "Team B"]},
        "createProgressBar": {"slideIndex": slide, "percent": 0.65, "x": 100, "y": 250, "width": 400, "height": 35},
        "createStyledTable": {"slideIndex": slide, "x": 80, "y": 80, "width": 560, "height": 240, "rows": 3, "cols": 3},
        "createTimeline": {"slideIndex": slide, "points": ["Plan", "Build", "Ship"]},
        "deletePptImage": {"slideIndex": slide, "shapeIndex": int(state["ppt_image_id"])},
        "deleteShape": {"slideIndex": slide, "shapeIndex": int(state["ppt_duplicate_shape_id"])},
        "deleteSlide": {"slideIndex": int(state["ppt_duplicate_slide"])},
        "deleteTextBox": {"slideIndex": slide, "shapeIndex": int(state["ppt_textbox_id"])},
        "distributeShapes": {"slideIndex": slide, "distribute": "horizontal"},
        "duplicateShape": {"slideIndex": slide, "shapeIndex": shape},
        "duplicateSlide": {"slideIndex": slide},
        "exportSlideAsImage": {"slideIndex": slide, "format": "PNG", "width": 1280, "height": 720, "outputPath": state["ppt_slide_image"]},
        "findPptText": {"find_text": "PPT_FIND_TOKEN"},
        "getAnimations": {"slideIndex": slide},
        "getPptTableCell": {"slideIndex": slide, "shapeIndex": int(state["ppt_table_id"]), "row": 1, "col": 1},
        "getShapes": {"slideIndex": slide},
        "getSlideInfo": {"slideIndex": slide},
        "getSlideNotes": {"slideIndex": slide},
        "getSlideTitle": {"slideIndex": slide},
        "getTextBoxes": {"slideIndex": slide},
        "groupShapes": {"slideIndex": slide},
        "insertImage": {"slideIndex": slide, "x": 360, "y": 80, "imagePath": state["fixture_image"], "width": 100, "height": 100},
        "insertPptChart": {"slideIndex": slide, "x": 100, "y": 100, "chartType": "column"},
        "insertPptImage": {"slideIndex": slide, "x": 220, "y": 80, "imagePath": state["fixture_image"], "width": 100, "height": 100},
        "insertPptTable": {"slideIndex": slide, "x": 80, "y": 200, "width": 560, "height": 220, "rows": 3, "cols": 3},
        "insertSlidesFromFile": {"afterIndex": int(state["ppt_slide_count"]), "slideStart": 1, "slideEnd": 1, "filePath": state["ppt_secondary_path"]},
        "moveSlide": {"slideIndex": int(state["ppt_duplicate_slide"]), "targetIndex": 2},
        "openPresentation": {"filePath": state["ppt_secondary_path"]},
        "removeAnimation": {"slideIndex": slide, "index": 1},
        "removePptHyperlink": {"slideIndex": slide, "shapeIndex": int(state["ppt_table_id"])},
        "removeSlideTransition": {"slideIndex": slide},
        "replacePptImage": {"slideIndex": slide, "shapeIndex": int(state["ppt_replace_image_id"]), "filePath": state["fixture_image"]},
        "replacePptText": {"find": "PPT_FIND_TOKEN", "replace": "PPT_REPLACED_TOKEN"},
        "saveAs": {"filePath": state["ppt_final_path"], "overwrite": True},
        "setBackgroundColor": {"slideIndex": slide, "color": "#F2F2F2"},
        "setBackgroundGradient": {"slideIndex": slide},
        "setBackgroundImage": {"slideIndex": slide, "imagePath": state["fixture_image"]},
        "setFontColor": {"slideIndex": slide, "color": "#203864"},
        "setMasterBackground": {"color": "#FFFFFF"},
        "setPptDateTime": {"text": "2026-08-28"},
        "setPptFooter": {"text": "WPS full suite"},
        "setPptTableCell": {"slideIndex": slide, "shapeIndex": int(state["ppt_table_id"]), "row": 1, "col": 1, "text": "PPT_TABLE_TOKEN"},
        "setSelectedText": {"text": "PPT_SELECTION_TOKEN"},
        "setShapeBorder": {"slideIndex": slide, "shapeIndex": shape, "color": "#203864", "width": 2},
        "setShapeFill": {"slideIndex": slide, "shapeIndex": shape, "color": "#5B9BD5"},
        "setShapePosition": {"slideIndex": slide, "shapeIndex": shape, "x": 80, "y": 100, "width": 200, "height": 110},
        "setShapeStyle": {"slideIndex": slide, "shapeIndex": shape, "fillColor": "#D9EAF7", "borderColor": "#4472C4", "borderWidth": 2},
        "setShapeText": {"slideIndex": slide, "shapeIndex": shape, "text": "PPT_SHAPE_TOKEN"},
        "setShapeTransparency": {"slideIndex": slide, "shapeIndex": shape, "value": 0.2},
        "setShapeZOrder": {"slideIndex": slide, "shapeIndex": shape, "order": "front"},
        "setSlideBackground": {"slideIndex": slide, "color": "#FFFFFF"},
        "setSlideContent": {"slideIndex": slide, "content": "PPT_FIND_TOKEN body content"},
        "setSlideLayout": {"slideIndex": slide, "layout": "title_content"},
        "setSlideNotes": {"slideIndex": slide, "text": "PPT_NOTES_TOKEN"},
        "setSlideNumber": {"show": True},
        "setSlideSize": {"width": 960, "height": 540},
        "setSlideSubtitle": {"slideIndex": slide, "subtitle": "PPT_SUBTITLE_TOKEN"},
        "setSlideTitle": {"slideIndex": slide, "title": "PPT_TITLE_TOKEN"},
        "setSlideTransition": {"slideIndex": slide, "transitionType": 1},
        "setTextBoxStyle": {"slideIndex": slide, "shapeIndex": int(state["ppt_textbox_id"]), "font_size": 18, "bold": True, "color": "#203864"},
        "setTextBoxText": {"slideIndex": slide, "shapeIndex": int(state["ppt_textbox_id"]), "text": "PPT_TEXTBOX_UPDATED_TOKEN"},
        "smartDistribute": {"slideIndex": slide, "distribute": "horizontal"},
        "switchPresentation": {"name": state["ppt_main_name"]},
        "switchSlide": {"slideIndex": slide},
        "unifyFont": {"font": "Microsoft YaHei"},
    }
    return dict(p.get(action, {}))


def _word_params(action: str, state: dict) -> dict:
    p = {
        "addComment": {"text": "WPS full suite comment"},
        "applyStyle": {"range": 1, "style_name": "Heading 1"},
        "convertFormat": {"outputPath": state["word_converted_path"], "overwrite": True, "targetFormat": "docx"},
        "convertToPDF": {"outputPath": state["word_pdf_path"], "overwrite": True},
        "findInDocument": {"find_text": "WORD_FIND_TOKEN", "match_case": True, "match_whole_word": False, "max_results": 20},
        "findReplace": {"find_text": "WORD_FIND_TOKEN", "replace_text": "WORD_REPLACED_TOKEN", "replace_all": True, "match_case": True, "match_whole_word": False},
        "generateTOC": {"levels": 3},
        "insertBookmark": {"name": "WpsSuiteBookmark"},
        "insertFooter": {"text": "WPS full suite footer"},
        "insertHeader": {"text": "WPS full suite header"},
        "insertImage": {"imagePath": state["fixture_image"], "width": 80, "height": 80},
        "insertTable": {"rows": 3, "cols": 3},
        "insertText": {"position": "end", "new_paragraph": True, "text": "WPS full suite heading\nWORD_FIND_TOKEN\nSuiteField: PLACEHOLDER"},
        "openDocument": {"filePath": state["word_open_path"]},
        "replaceBookmarkContent": {"name": "WpsSuiteBookmark", "text": "WORD_BOOKMARK_TOKEN"},
        "saveAs": {"filePath": state["word_final_path"], "overwrite": True},
        "setFont": {"range": "all", "font_name": "Microsoft YaHei", "font_size": 11, "bold": False, "italic": False, "underline": False, "color": "#203864"},
        "setLineSpacing": {"paragraphIndex": 1, "lineSpacing": 18},
        "setPageSetup": {"orientation": "portrait", "marginTop": 72, "marginBottom": 72, "marginLeft": 72, "marginRight": 72},
        "setParagraph": {"paragraphIndex": 1, "alignment": "left", "lineSpacing": 18},
        "setSelectedText": {"text": "WORD_SELECTION_TOKEN"},
        "setTextColor": {"range": "WORD_FIND_TOKEN", "color": "#C00000"},
        "smartFillField": {"keyword": "SuiteField:", "value": "WORD_FIELD_TOKEN"},
        "switchDocument": {"name": state["word_main_name"]},
    }
    return dict(p.get(action, {}))


def build_action_params(owner: str, action: str, state: dict) -> dict:
    """Build a valid, deterministic parameter object for one live Action case."""

    if owner == "bridge":
        return {}
    if owner == "excel":
        return _excel_params(action, state)
    if owner == "ppt":
        return _ppt_params(action, state)
    if owner == "word":
        return _word_params(action, state)
    raise ValueError(f"unsupported suite owner: {owner}")
